### ISSUE TITLE
seems not to work

### ISSUE THREAD

**Issue by pedalracer** [mxro/autohotkey-chatgpt-voice#1] opened 2024-02-07 14:30 UTC
Hey I am installed your script with my API under /documents/scripts and installed AHK V.1
I have default mic and speaker working under other programs but I cannot hear any answers from your script nor am I am sure it is working at all.
So, might it be to the /*.exe in your script and that I need to put the script outside my /document folder?

**Comment by mxro** [comment] 2024-02-10 05:43
Hello and thank you for raising this issue!

Do you see a white 'H' on green background in the background apps?

![image](https://github.com/mxro/autohotkey-chatgpt-voice/assets/1448524/d45e6998-c4c0-4c8e-b021-91a8d34f3e2a)

That would be the instance of autohotkey that is supposed to call the script.

If you see that, you can right click the 'H' and then select 'Open' - this shows the logs of what is received and maybe can help point us to the problem!

**Comment by pedalracer** [comment] 2024-02-10 11:29
`Script lines most recently executed (oldest first).  Press [F5] to refresh.  The seconds elapsed between a line and the one after it is in parentheses to the right (if not 0).  The bottommost line's elapsed time is the number of seconds since it executed.

---- C:\Users\Boris\Documents\AutoHotKey\Autohotkey-ChatGPT\watch.ahk
002: Return (242.39)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide (0.03)
007: }
014: Return (0.48)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide (0.20)
013: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.05)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.02)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide (0.03)
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide (0.03)
007: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.02)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide (0.03)
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (0.02)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide (0.03)
013: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide (0.03)
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (0.01)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (0.02)
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return
003: NotRecording := !NotRecording
004: if NotRecording  
006: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide
007: }
014: Return (0.03)
003: NotRecording := !NotRecording
004: if NotRecording  
010: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
011: Sleep,100 (0.11)
012: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide
013: }
014: Return (3.36)

Press [F5] to refresh.`

**Comment by pedalracer** [comment] 2024-02-10 11:30
Thank you for being 'there' and helping me.

The log is from the time span I pressed and hold F8 and asked 'How far is the moon from earth' and then I released F8. ;)

**Comment by mxro** [comment] 2024-02-11 00:12
Thank you for sending through the information! Happy to work through this until we've got it working!

For reference, I have provided below the output of what should happen when F8 is pressed, I speak the command, and then press F8 again to stop the recording.

```
012: NotRecording := !NotRecording
013: if NotRecording  
015: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide (0.03)
016: }
023: Return (1.34)
012: NotRecording := !NotRecording
013: if NotRecording  
019: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --globcmd=stop,,Hide
020: Sleep,100 (0.11)
021: Run,%A_WorkingDir%\bin\whisper-autohotkey\whisper-autohotkey.exe,,Hide (0.48)
022: }
023: Return (14.75)
```

To me, that looks very similar to what is running for you! The difference is that for me the recording command returns after a longer time (1.34 s)

```
015: Run,%A_WorkingDir%\bin\fmedia-1.31-windows-x64\fmedia\fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3 --globcmd=listen,,Hide (0.03)
016: }
023: Return (1.34)
```

Whereas for you it always seems to return after 0.03 s.

In the folder where the watch script is located, do you have a file `rec.mp3` - that should be created once the recording is successful. If you have the file, you can open it and see if anything is recorded.

Can you try if fmedia is working correctly for you?

For this, you can open a CMD terminal in the folder the watch file is located and then go to `cd bin\fmedia-1.31-windows-x64`

In that folder, then run:

```
fmedia.exe --record --overwrite --mpeg-quality=16 --rate=12000 --out=rec.mp3
```

**Comment by pedalracer** [comment] 2024-02-12 09:04
Ok,
the test prompt works and fmedia records. The .mp3 is then recorded in the bin fmedia-1.31-windows-x64 folder.
Testing the watch.ahk a mp3 file is created, too. But it never exceeds 1.52 kbyte. So, it is not recording!

I run the script in /mydocuments and also under C:/ahkscripts.


I hope, it helps. Thank you.

**Comment by mxro** [comment] 2024-02-14 02:29
Just saw this in your earlier comment:

> The log is from the time span I pressed and hold F8 and asked 'How far is the moon from earth' and then I released F8. ;)

The script is designed in the following way:

- Press F8 once (so press and release)
- Start speaking
- Press F8 again

On second time pressing F8, the recording should be stopped.

Does that work?

**Comment by mxro** [comment] 2024-12-23 00:30
Closing this for now - if the issue is still present or a new one appears, please be welcome to open a new issue.

**Closed as completed by mxro** 2024-12-23 00:30 UTC
